kernel: selinux: Fix build error
* d77ab8d although fixed some typo, but since there
  is no include avc.h, this will cause the build to fail
* Error:

/mnt/HDD/fish/aospa/kernel/msm-4.9/drivers/staging/ksu/selinux/selinux.c:60:2: error: use of undeclared identifier 'selinux_enforcing'
        selinux_enforcing = enforce;
        ^
/mnt/HDD/fish/aospa/kernel/msm-4.9/drivers/staging/ksu/selinux/selinux.c:81:9: error: use of undeclared identifier 'selinux_enforcing'
        return selinux_enforcing;
               ^
2 errors generated.

Change-Id: I4cc8917b2b73ca467873222e02d498da8718988e