kernel: Include task_stack.h unconditionally in syscall_hook_manager
task_pt_regs() expands to task_stack_page(), which is defined in
<linux/sched/task_stack.h>. This include was incorrectly guarded behind
LINUX_VERSION_CODE < 6.7.0 grouped with the unrelated coompat.h, on
most kernel configs the header happens to be pulled in transitively
through other includes, but this fragile and incorrect.

  error: implicit declaration of function 'task_stack_page'

Move the include outside the version guard. task_pt_regs() needs
task_stack_page() unconditionally.

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>